
POST http://localhost:3000/login 
Content-Type: application/json

{
  "username": "shiva",
  "password": "shiva123"
}
###

POST http://localhost:3000/signup
Content-Type: application/json

{
  "username":"vivek",
  "password":"vivek123",
  "email":"vivek2024@gmail.com"
}
###
